/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    CuisineShowcaseComp: typeof import('./src/components/CuisineShowcaseComp.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FooterComp: typeof import('./src/components/FooterComp.vue')['default']
    GroceryCompareCard: typeof import('./src/components/GroceryCompareCard.vue')['default']
    HeroComp: typeof import('./src/components/HeroComp.vue')['default']
    IconCookkart: typeof import('./src/components/icons/IconCookkart.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NavTop: typeof import('./src/components/NavTop.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultCard: typeof import('./src/components/SearchResultCard.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
